1 remaining error in compile
1 remaining error

.\src\Model\Player.cs(222,9): error CS0305: Using the generic type `System.Collections.Generic.IEnumerator<T>' requires `1' type argument(s)